include test, run on GH runner

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -12,23 +12,25 @@ on:
 
 env:
   REGISTRY_IMAGE: yfhme/openssl-docker
+  TEST_TAG: yfhme/openssl-docker:test
 
 jobs:
   build:
-    strategy:
-      fail-fast: true
-      matrix:
-        include:
-          - platform: "linux/arm64"
-            arch: "ARM64"
-          - platform: "linux/amd64"
-            arch: "x64"
-    runs-on: [self-hosted, "${{ matrix.arch }}"]
+    runs-on: ubuntu-latest
+    #strategy:
+    #  fail-fast: true
+    #  matrix:
+    #    include:
+    #      - platform: "linux/arm64"
+    #        arch: "ARM64"
+    #      - platform: "linux/amd64"
+    #        arch: "x64"
+    #runs-on: [self-hosted, "${{ matrix.arch }}"]
 
     steps:
-      - name: Cleanout old digests for self-hosted runs
-        run: |
-          rm -rf /tmp/digests || true
+      #- name: Cleanout old digests for self-hosted runs
+      #  run: |
+      #    rm -rf /tmp/digests || true
 
       - name: Checkout
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
@@ -38,11 +40,9 @@ jobs:
         uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0
         with:
           images: ${{ env.REGISTRY_IMAGE }}
-          flavor: |
-            latest=false
 
-      #- name: Set up QEMU
-      #  uses: docker/setup-qemu-action@v3.0.0
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
@@ -52,6 +52,16 @@ jobs:
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build and export to Docker
+        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
+        with:
+          context: .
+          load: true
+          tags: ${{ env.TEST_TAG }}
+      - name: Test
+        run: |
+          docker run --rm ${{ env.TEST_TAG }} bin/openssl version -a
 
       - name: Build and push by digest
         id: build
@@ -59,55 +69,53 @@ jobs:
         with:
           context: .
           push: ${{ github.event_name != 'pull_request' }}
-          platforms: ${{ matrix.platform }}
+          platforms: linux/amd64,linux/arm64
           labels: ${{ steps.meta.outputs.labels }}
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
-          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
+          #outputs: type=image,name=${{ env.REGISTRY_IMAGE }},name-canonical=true,push=true
 
-      - name: Export digest
-        run: |
-          mkdir -p /tmp/digests
-          digest="${{ steps.build.outputs.digest }}"
-          touch "/tmp/digests/${digest#sha256:}"
+      #- name: Export digest
+      #  run: |
+      #    mkdir -p /tmp/digests
+      #    digest="${{ steps.build.outputs.digest }}"
+      #    touch "/tmp/digests/${digest#sha256:}"
 
-      - name: Upload digest
-        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
-        with:
-          name: digests
-          path: /tmp/digests/*
-          if-no-files-found: error
-          retention-days: 1
+      #- name: Upload digest
+      #  uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
+      #  with:
+      #    name: digests
+      #    path: /tmp/digests/*
+      #    if-no-files-found: error
+      #    retention-days: 1
 
-  merge:
-    runs-on: ubuntu-latest
-    needs:
-      - build
-    steps:
-      - name: Download digests
-        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
-        with:
-          name: digests
-          path: /tmp/digests
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0
-        with:
-          images: ${{ env.REGISTRY_IMAGE }}
-          flavor: |
-            latest=false
-      - name: Login to Docker Hub
-        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Create manifest list and push
-        working-directory: /tmp/digests
-        run: |
-          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
-            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
-      - name: Inspect image
-        run: |
-          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
+  #merge:
+  #  runs-on: ubuntu-latest
+  #  needs:
+  #    - build
+  #  steps:
+  #    - name: Download digests
+  #      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
+  #      with:
+  #        name: digests
+  #        path: /tmp/digests
+  #    - name: Set up Docker Buildx
+  #      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
+  #    - name: Docker meta
+  #      id: meta
+  #      uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0
+  #      with:
+  #        images: ${{ env.REGISTRY_IMAGE }}
+  #        flavor: |
+  #          latest=false
+  #    - name: Login to Docker Hub
+  #      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
+  #      with:
+  #        username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #        password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #    - name: Create manifest list and push
+  #      working-directory: /tmp/digests
+  #      run: |
+  #        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
+  #          $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
+  #    - name: Inspect image
+  #      run: |
+  #        docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
